### ISSUE TITLE
[rio_de_hola] settings issue

### ISSUE THREAD

**Issue by jakoch** [fifengine/fifengine-demos#14]
- Windows 
- fifengine master
- fifengine-demos master

Traceback:
```
D:\fifesdk\fifengine-demos-master\rio_de_hola>d:\fifesdk\python\python.exe run.py
Using the FIFE python module found here:  d:\fifesdk\python\lib\site-packages\fife
Traceback (most recent call last):
  File "run.py", line 179, in <module>
    main()
  File "run.py", line 162, in main
    app = IslandDemo()
  File "run.py", line 137, in __init__
    super(IslandDemo,self).__init__(TDS)
  File "d:\fifesdk\python\lib\site-packages\fife\extensions\pychan\pychanbasicapplication.py", line 69, in __init__
    super(PychanApplicationBase, self).__init__(setting)
  File "d:\fifesdk\python\lib\site-packages\fife\extensions\basicapplication.py", line 77, in __init__
    self.initLogging()
  File "d:\fifesdk\python\lib\site-packages\fife\extensions\basicapplication.py", line 185, in initLogging
    self._setting.get("FIFE", "LogToFile", False))
  File "d:\fifesdk\python\lib\site-packages\fife\extensions\fifelog.py", line 42, in __init__
    self.lm.setLogToPrompt(promptlog)
  File "d:\fifesdk\python\lib\site-packages\fife\fife.py", line 14950, in setLogToPrompt
    return _fife.LogManager_setLogToPrompt(self, logtoprompt)
TypeError: in method 'LogManager_setLogToPrompt', argument 2 of type 'bool'
```

**Comment by prock-fife** [comment]
seems to me I had that same issue.   try deleting your settings.xml and re-run rio.

**Comment by jakoch** [comment]
The settings.xml isn't generated, it crashes before doing that.

**Comment by Niektory** [comment]
Please double-check that there's really no settings.xml (it should be in `%appdata%\fife\rio_de_hola\`) and that you're really using the master versions.

**Comment by jakoch** [comment]
Thank you for reminding me! I deleted `%appdata%\fife` and now it works!
We should merge your "settings.xml in current folder" change.
